version: '3'
services:
  app:
    build: .
    depends_on:
      - db  
    environment:
      DB_USER: ${DB_USER}  
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}  
      DB_HOST: db
    volumes: 
      - ./assets:/root/assets  
    restart: "no"

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    restart: "no"
 